from core.base.button import Button

# This file was automatically generated by tools/button_extract.py.
# Do not modify it manually.

BTN_SEED_SELECT_POPUP_RIGHT = Button(area={'qq': (511, 608, 524, 636), 'wechat': (511, 608, 524, 636)}, color={'qq': (226, 206, 123), 'wechat': (226, 206, 123)}, button={'qq': (511, 608, 524, 636), 'wechat': (511, 608, 524, 636)}, file={'qq': 'templates/qq/btn/BTN_SEED_SELECT_POPUP_RIGHT.png', 'wechat': 'templates/qq/btn/BTN_SEED_SELECT_POPUP_RIGHT.png'}, name='BTN_SEED_SELECT_POPUP_RIGHT')
BTN_BATCH_SELL = Button(area={'qq': (325, 867, 430, 901), 'wechat': (325, 867, 430, 901)}, color={'qq': (178, 196, 72), 'wechat': (178, 196, 72)}, button={'qq': (325, 867, 430, 901), 'wechat': (325, 867, 430, 901)}, file={'qq': 'templates/qq/btn/btn_batch_sell.png', 'wechat': 'templates/qq/btn/btn_batch_sell.png'}, name='btn_batch_sell')  # 批量出售
BTN_BUG = Button(area={'qq': (332, 683, 372, 717), 'wechat': (332, 683, 372, 717)}, color={'qq': (152, 125, 112), 'wechat': (152, 125, 112)}, button={'qq': (332, 683, 372, 717), 'wechat': (332, 683, 372, 717)}, file={'qq': 'templates/qq/btn/btn_bug.png', 'wechat': 'templates/qq/btn/btn_bug.png'}, name='btn_bug')  # 一键除虫
BTN_CLAIM = Button(area={'qq': (327, 733, 424, 759), 'wechat': (327, 733, 424, 759)}, color={'qq': (196, 204, 122), 'wechat': (196, 204, 122)}, button={'qq': (327, 733, 424, 759), 'wechat': (327, 733, 424, 759)}, file={'qq': 'templates/qq/btn/btn_claim.png', 'wechat': 'templates/qq/btn/btn_claim.png'}, name='btn_claim')  # 领取
BTN_CLICK_TO_CLOSE = Button(area={'qq': (207, 793, 331, 811), 'wechat': (207, 793, 331, 811)}, color={'qq': (148, 141, 129), 'wechat': (148, 141, 129)}, button={'qq': (207, 793, 331, 811), 'wechat': (207, 793, 331, 811)}, file={'qq': 'templates/qq/btn/btn_click_to_close.png', 'wechat': 'templates/qq/btn/btn_click_to_close.png'}, name='btn_click_to_close')
BTN_CLOSE = Button(area={'qq': (493, 54, 527, 88), 'wechat': (493, 54, 527, 88)}, color={'qq': (236, 191, 165), 'wechat': (236, 191, 165)}, button={'qq': (493, 54, 527, 88), 'wechat': (493, 54, 527, 88)}, file={'qq': 'templates/qq/btn/btn_close.png', 'wechat': 'templates/qq/btn/btn_close.png'}, name='btn_close')  # 关闭
BTN_COME_AGAIN = Button(area={'qq': (223, 590, 316, 613), 'wechat': (223, 590, 316, 613)}, color={'qq': (187, 199, 98), 'wechat': (187, 199, 98)}, button={'qq': (223, 590, 316, 613), 'wechat': (223, 590, 316, 613)}, file={'qq': 'templates/qq/btn/btn_come_again.png', 'wechat': 'templates/qq/btn/btn_come_again.png'}, name='btn_come_again')
BTN_CONFIRM = Button(area={'qq': (349, 871, 403, 896), 'wechat': (349, 871, 403, 896)}, color={'qq': (182, 197, 86), 'wechat': (182, 197, 86)}, button={'qq': (349, 871, 403, 896), 'wechat': (349, 871, 403, 896)}, file={'qq': 'templates/qq/btn/btn_confirm.png', 'wechat': 'templates/qq/btn/btn_confirm.png'}, name='btn_confirm')  # 确认
BTN_EXPAND = Button(area={'qq': (160, 574, 192, 587), 'wechat': (160, 574, 192, 587)}, color={'qq': (182, 116, 57), 'wechat': (182, 116, 57)}, button={'qq': (160, 574, 192, 587), 'wechat': (160, 574, 192, 587)}, file={'qq': 'templates/qq/btn/btn_expand.png', 'wechat': 'templates/qq/btn/btn_expand.png'}, name='btn_expand')  # 扩建
BTN_EXPAND_CONFIRM = Button(area={'qq': (245, 570, 295, 595), 'wechat': (245, 570, 295, 595)}, color={'qq': (190, 201, 105), 'wechat': (190, 201, 105)}, button={'qq': (245, 570, 295, 595), 'wechat': (245, 570, 295, 595)}, file={'qq': 'templates/qq/btn/btn_expand_confirm.png', 'wechat': 'templates/qq/btn/btn_expand_confirm.png'}, name='btn_expand_confirm')
BTN_EXPAND_DIRECT_CONFIRM = Button(area={'qq': (245, 570, 295, 595), 'wechat': (245, 570, 295, 595)}, color={'qq': (190, 201, 105), 'wechat': (190, 201, 105)}, button={'qq': (245, 570, 295, 595), 'wechat': (245, 570, 295, 595)}, file={'qq': 'templates/qq/btn/btn_expand_direct_confirm.png', 'wechat': 'templates/qq/btn/btn_expand_direct_confirm.png'}, name='btn_expand_direct_confirm')
BTN_FRIEND_AGREED = Button(area={'qq': (316, 687, 416, 713), 'wechat': (316, 687, 416, 713)}, color={'qq': (190, 200, 110), 'wechat': (190, 200, 110)}, button={'qq': (316, 687, 416, 713), 'wechat': (316, 687, 416, 713)}, file={'qq': 'templates/qq/btn/btn_friend_agreed.png', 'wechat': 'templates/qq/btn/btn_friend_agreed.png'}, name='btn_friend_agreed')
BTN_FRIEND_APPLY = Button(area={'qq': (220, 196, 318, 221), 'wechat': (220, 196, 318, 221)}, color={'qq': (226, 190, 167), 'wechat': (226, 190, 167)}, button={'qq': (220, 196, 318, 221), 'wechat': (220, 196, 318, 221)}, file={'qq': 'templates/qq/btn/btn_friend_apply.png', 'wechat': 'templates/qq/btn/btn_friend_apply.png'}, name='btn_friend_apply')
BTN_FRIEND_RIGHT_FRAME = Button(area={'qq': (135, 812, 152, 913), 'wechat': (135, 812, 152, 913)}, color={'qq': (211, 231, 143), 'wechat': (211, 231, 143)}, button={'qq': (135, 812, 152, 913), 'wechat': (135, 812, 152, 913)}, file={'qq': 'templates/qq/btn/btn_friend_right_frame.png', 'wechat': 'templates/qq/btn/btn_friend_right_frame.png'}, name='btn_friend_right_frame')
BTN_HARVEST = Button(area={'qq': (246, 688, 287, 720), 'wechat': (246, 688, 287, 720)}, color={'qq': (221, 169, 139), 'wechat': (221, 169, 139)}, button={'qq': (246, 688, 287, 720), 'wechat': (246, 688, 287, 720)}, file={'qq': 'templates/qq/btn/btn_harvest.png', 'wechat': 'templates/qq/btn/btn_harvest.png'}, name='btn_harvest')  # 一键收获
BTN_HOME = Button(area={'qq': (465, 697, 510, 729), 'wechat': (465, 697, 510, 729)}, color={'qq': (181, 126, 76), 'wechat': (181, 126, 76)}, button={'qq': (465, 697, 510, 729), 'wechat': (465, 697, 510, 729)}, file={'qq': 'templates/qq/btn/btn_home.png', 'wechat': 'templates/qq/btn/btn_home.png'}, name='btn_home')  # 回家
BTN_LABOR_IS_GLORIOUS = Button(area={'qq': (135, 440, 176, 452), 'wechat': (135, 440, 176, 452)}, color={'qq': (196, 143, 78), 'wechat': (196, 143, 78)}, button={'qq': (135, 440, 176, 452), 'wechat': (135, 440, 176, 452)}, file={'qq': 'templates/qq/btn/btn_labor_is_glorious.png', 'wechat': 'templates/qq/btn/btn_labor_is_glorious.png'}, name='btn_labor_is_glorious')
BTN_LAND_LEFT = Button(area={'qq': (43, 590, 59, 614), 'wechat': (43, 590, 59, 614)}, color={'qq': (192, 200, 87), 'wechat': (192, 200, 87)}, button={'qq': (43, 590, 59, 614), 'wechat': (43, 590, 59, 614)}, file={'qq': 'templates/qq/btn/btn_land_left.png', 'wechat': 'templates/qq/btn/btn_land_left.png'}, name='btn_land_left')
BTN_LAND_RIGHT = Button(area={'qq': (482, 547, 498, 571), 'wechat': (482, 547, 498, 571)}, color={'qq': (171, 197, 84), 'wechat': (171, 197, 84)}, button={'qq': (482, 547, 498, 571), 'wechat': (482, 547, 498, 571)}, file={'qq': 'templates/qq/btn/btn_land_right.png', 'wechat': 'templates/qq/btn/btn_land_right.png'}, name='btn_land_right')
BTN_LOGIN_AGAIN = Button(area={'qq': (325, 572, 423, 598), 'wechat': (325, 572, 423, 598)}, color={'qq': (195, 203, 121), 'wechat': (195, 203, 121)}, button={'qq': (325, 572, 423, 598), 'wechat': (325, 572, 423, 598)}, file={'qq': 'templates/qq/btn/btn_login_again.png', 'wechat': 'templates/qq/btn/btn_login_again.png'}, name='btn_login_again')
BTN_MATURE = Button(area={'qq': (261, 457, 278, 479), 'wechat': (261, 457, 278, 479)}, color={'qq': (201, 181, 78), 'wechat': (201, 181, 78)}, button={'qq': (261, 457, 278, 479), 'wechat': (261, 457, 278, 479)}, file={'qq': 'templates/qq/btn/btn_mature.png', 'wechat': 'templates/qq/btn/btn_mature.png'}, name='btn_mature')
BTN_ORDINARY_FERTILIZER = Button(area={'qq': (115, 610, 159, 642), 'wechat': (115, 610, 159, 642)}, color={'qq': (200, 134, 76), 'wechat': (200, 134, 76)}, button={'qq': (115, 610, 159, 642), 'wechat': (115, 610, 159, 642)}, file={'qq': 'templates/qq/btn/btn_ordinary_fertilizer.png', 'wechat': 'templates/qq/btn/btn_ordinary_fertilizer.png'}, name='btn_ordinary_fertilizer')
BTN_ORGANIC_FERTILIZER = Button(area={'qq': (202, 613, 248, 640), 'wechat': (202, 613, 248, 640)}, color={'qq': (175, 139, 35), 'wechat': (175, 139, 35)}, button={'qq': (202, 613, 248, 640), 'wechat': (202, 613, 248, 640)}, file={'qq': 'templates/qq/btn/btn_organic_fertilizer.png', 'wechat': 'templates/qq/btn/btn_organic_fertilizer.png'}, name='btn_organic_fertilizer')
BTN_PLANTING = Button(area={'qq': (233, 866, 307, 893), 'wechat': (233, 866, 307, 893)}, color={'qq': (190, 201, 107), 'wechat': (190, 201, 107)}, button={'qq': (233, 866, 307, 893), 'wechat': (233, 866, 307, 893)}, file={'qq': 'templates/qq/btn/btn_planting.png', 'wechat': 'templates/qq/btn/btn_planting.png'}, name='btn_planting')
BTN_SHARE_GREEN = Button(area={'qq': (356, 753, 406, 778), 'wechat': (356, 753, 406, 778)}, color={'qq': (178, 195, 76), 'wechat': (178, 195, 76)}, button={'qq': (356, 753, 406, 778), 'wechat': (356, 753, 406, 778)}, file={'qq': 'templates/qq/btn/btn_share_green.png', 'wechat': 'templates/qq/btn/btn_share_green.png'}, name='btn_share_green')
BTN_SHARE_YELLOW = Button(area={'qq': (139, 733, 190, 760), 'wechat': (139, 733, 190, 760)}, color={'qq': (223, 185, 102), 'wechat': (223, 185, 102)}, button={'qq': (139, 733, 190, 760), 'wechat': (139, 733, 190, 760)}, file={'qq': 'templates/qq/btn/btn_share_yellow.png', 'wechat': 'templates/qq/btn/btn_share_yellow.png'}, name='btn_share_yellow')
BTN_SHOP_BUY_CHECK = Button(area={'qq': (247, 268, 293, 292), 'wechat': (247, 268, 293, 292)}, color={'qq': (233, 200, 183), 'wechat': (233, 200, 183)}, button={'qq': (247, 268, 293, 292), 'wechat': (247, 268, 293, 292)}, file={'qq': 'templates/qq/btn/btn_shop_buy_check.png', 'wechat': 'templates/qq/btn/btn_shop_buy_check.png'}, name='btn_shop_buy_check')
BTN_SHOP_BUY_CONFIRM = Button(area={'qq': (246, 622, 295, 648), 'wechat': (246, 622, 295, 648)}, color={'qq': (189, 200, 104), 'wechat': (189, 200, 104)}, button={'qq': (246, 622, 295, 648), 'wechat': (246, 622, 295, 648)}, file={'qq': 'templates/qq/btn/btn_shop_buy_confirm.png', 'wechat': 'templates/qq/btn/btn_shop_buy_confirm.png'}, name='btn_shop_buy_confirm')
BTN_STEAL = Button(area={'qq': (248, 692, 284, 720), 'wechat': (248, 692, 284, 720)}, color={'qq': (187, 147, 123), 'wechat': (187, 147, 123)}, button={'qq': (248, 692, 284, 720), 'wechat': (248, 692, 284, 720)}, file={'qq': 'templates/qq/btn/btn_steal.png', 'wechat': 'templates/qq/btn/btn_steal.png'}, name='btn_steal')
BTN_TASK_CLAIM = Button(area={'qq': (414, 475, 456, 495), 'wechat': (414, 475, 456, 495)}, color={'qq': (181, 195, 88), 'wechat': (181, 195, 88)}, button={'qq': (414, 475, 456, 495), 'wechat': (414, 475, 456, 495)}, file={'qq': 'templates/qq/btn/btn_task_claim.png', 'wechat': 'templates/qq/btn/btn_task_claim.png'}, name='btn_task_claim')
BTN_VISIT_FIRST = Button(area={'qq': (443, 295, 480, 314), 'wechat': (443, 295, 480, 314)}, color={'qq': (183, 195, 99), 'wechat': (183, 195, 99)}, button={'qq': (443, 295, 480, 314), 'wechat': (443, 295, 480, 314)}, file={'qq': 'templates/qq/btn/btn_visit_first.png', 'wechat': 'templates/qq/btn/btn_visit_first.png'}, name='btn_visit_first')
BTN_WATER = Button(area={'qq': (160, 683, 200, 717), 'wechat': (160, 683, 200, 717)}, color={'qq': (167, 157, 156), 'wechat': (167, 157, 156)}, button={'qq': (160, 683, 200, 717), 'wechat': (160, 683, 200, 717)}, file={'qq': 'templates/qq/btn/btn_water.png', 'wechat': 'templates/qq/btn/btn_water.png'}, name='btn_water')  # 一键浇水
BTN_WEED = Button(area={'qq': (246, 683, 286, 717), 'wechat': (246, 683, 286, 717)}, color={'qq': (161, 158, 110), 'wechat': (161, 158, 110)}, button={'qq': (246, 683, 286, 717), 'wechat': (246, 683, 286, 717)}, file={'qq': 'templates/qq/btn/btn_weed.png', 'wechat': 'templates/qq/btn/btn_weed.png'}, name='btn_weed')  # 一键除草
FRIEND_CHECK = Button(area={'qq': (241, 69, 299, 98), 'wechat': (241, 69, 299, 98)}, color={'qq': (225, 186, 159), 'wechat': (225, 186, 159)}, button={'qq': (241, 69, 299, 98), 'wechat': (241, 69, 299, 98)}, file={'qq': 'templates/qq/ui/friend_check.png', 'wechat': 'templates/qq/ui/friend_check.png'}, name='friend_check')
ICON_BUG_IN_FRIEND_DETAIL = Button(area={'qq': (0, 0, 12, 15), 'wechat': (0, 0, 12, 15)}, color={'qq': (176, 189, 133), 'wechat': (176, 189, 133)}, button={'qq': (0, 0, 12, 15), 'wechat': (0, 0, 12, 15)}, file={'qq': 'templates/qq/icon/icon_bug_in_friend_detail.png', 'wechat': 'templates/qq/icon/icon_bug_in_friend_detail.png'}, name='icon_bug_in_friend_detail')
ICON_BUG_IN_FRIEND_LIST = Button(area={'qq': (0, 0, 24, 24), 'wechat': (0, 0, 24, 24)}, color={'qq': (167, 156, 153), 'wechat': (167, 156, 153)}, button={'qq': (0, 0, 24, 24), 'wechat': (0, 0, 24, 24)}, file={'qq': 'templates/qq/icon/icon_bug_in_friend_list.png', 'wechat': 'templates/qq/icon/icon_bug_in_friend_list.png'}, name='icon_bug_in_friend_list')
ICON_LAND_BLACK = Button(area={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, color={'qq': (92, 67, 42), 'wechat': (92, 67, 42)}, button={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, file={'qq': 'templates/qq/land/icon_land_black.png', 'wechat': 'templates/qq/land/icon_land_black.png'}, name='icon_land_black')
ICON_LAND_GOLD = Button(area={'qq': (0, 0, 19, 17), 'wechat': (0, 0, 19, 17)}, color={'qq': (249, 203, 50), 'wechat': (249, 203, 50)}, button={'qq': (0, 0, 19, 17), 'wechat': (0, 0, 19, 17)}, file={'qq': 'templates/qq/land/icon_land_gold.png', 'wechat': 'templates/qq/land/icon_land_gold.png'}, name='icon_land_gold')
ICON_LAND_GOLD_2 = Button(area={'qq': (0, 0, 19, 17), 'wechat': (0, 0, 19, 17)}, color={'qq': (249, 204, 51), 'wechat': (249, 204, 51)}, button={'qq': (0, 0, 19, 17), 'wechat': (0, 0, 19, 17)}, file={'qq': 'templates/qq/land/icon_land_gold_2.png', 'wechat': 'templates/qq/land/icon_land_gold_2.png'}, name='icon_land_gold_2')
ICON_LAND_RED = Button(area={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, color={'qq': (223, 87, 55), 'wechat': (223, 87, 55)}, button={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, file={'qq': 'templates/qq/land/icon_land_red.png', 'wechat': 'templates/qq/land/icon_land_red.png'}, name='icon_land_red')
ICON_LAND_STAND = Button(area={'qq': (0, 0, 19, 16), 'wechat': (0, 0, 19, 16)}, color={'qq': (178, 131, 74), 'wechat': (178, 131, 74)}, button={'qq': (0, 0, 19, 16), 'wechat': (0, 0, 19, 16)}, file={'qq': 'templates/qq/land/icon_land_stand.png', 'wechat': 'templates/qq/land/icon_land_stand.png'}, name='icon_land_stand')
ICON_NUM_0 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (147, 136, 119), 'wechat': (147, 136, 119)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_0.png', 'wechat': 'templates/qq/icon/icon_num_0.png'}, name='icon_num_0')
ICON_NUM_1 = Button(area={'qq': (0, 0, 5, 12), 'wechat': (0, 0, 5, 12)}, color={'qq': (161, 150, 131), 'wechat': (161, 150, 131)}, button={'qq': (0, 0, 5, 12), 'wechat': (0, 0, 5, 12)}, file={'qq': 'templates/qq/icon/icon_num_1.png', 'wechat': 'templates/qq/icon/icon_num_1.png'}, name='icon_num_1')
ICON_NUM_2 = Button(area={'qq': (0, 0, 8, 12), 'wechat': (0, 0, 8, 12)}, color={'qq': (162, 151, 132), 'wechat': (162, 151, 132)}, button={'qq': (0, 0, 8, 12), 'wechat': (0, 0, 8, 12)}, file={'qq': 'templates/qq/icon/icon_num_2.png', 'wechat': 'templates/qq/icon/icon_num_2.png'}, name='icon_num_2')
ICON_NUM_3 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (159, 148, 130), 'wechat': (159, 148, 130)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_3.png', 'wechat': 'templates/qq/icon/icon_num_3.png'}, name='icon_num_3')
ICON_NUM_4 = Button(area={'qq': (0, 0, 9, 11), 'wechat': (0, 0, 9, 11)}, color={'qq': (164, 153, 134), 'wechat': (164, 153, 134)}, button={'qq': (0, 0, 9, 11), 'wechat': (0, 0, 9, 11)}, file={'qq': 'templates/qq/icon/icon_num_4.png', 'wechat': 'templates/qq/icon/icon_num_4.png'}, name='icon_num_4')
ICON_NUM_5 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (146, 136, 118), 'wechat': (146, 136, 118)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_5.png', 'wechat': 'templates/qq/icon/icon_num_5.png'}, name='icon_num_5')
ICON_NUM_6 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (139, 129, 112), 'wechat': (139, 129, 112)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_6.png', 'wechat': 'templates/qq/icon/icon_num_6.png'}, name='icon_num_6')
ICON_NUM_7 = Button(area={'qq': (0, 0, 8, 12), 'wechat': (0, 0, 8, 12)}, color={'qq': (183, 172, 151), 'wechat': (183, 172, 151)}, button={'qq': (0, 0, 8, 12), 'wechat': (0, 0, 8, 12)}, file={'qq': 'templates/qq/icon/icon_num_7.png', 'wechat': 'templates/qq/icon/icon_num_7.png'}, name='icon_num_7')
ICON_NUM_8 = Button(area={'qq': (0, 0, 7, 12), 'wechat': (0, 0, 7, 12)}, color={'qq': (137, 127, 111), 'wechat': (137, 127, 111)}, button={'qq': (0, 0, 7, 12), 'wechat': (0, 0, 7, 12)}, file={'qq': 'templates/qq/icon/icon_num_8.png', 'wechat': 'templates/qq/icon/icon_num_8.png'}, name='icon_num_8')
ICON_NUM_9 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (139, 129, 112), 'wechat': (139, 129, 112)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_9.png', 'wechat': 'templates/qq/icon/icon_num_9.png'}, name='icon_num_9')
ICON_NUM_LEFT = Button(area={'qq': (0, 0, 8, 26), 'wechat': (0, 0, 8, 26)}, color={'qq': (191, 171, 95), 'wechat': (191, 171, 95)}, button={'qq': (0, 0, 8, 26), 'wechat': (0, 0, 8, 26)}, file={'qq': 'templates/qq/icon/icon_num_left.png', 'wechat': 'templates/qq/icon/icon_num_left.png'}, name='icon_num_left')
ICON_STEAL_IN_FRIEND_DETAIL = Button(area={'qq': (0, 0, 13, 20), 'wechat': (0, 0, 13, 20)}, color={'qq': (176, 142, 113), 'wechat': (176, 142, 113)}, button={'qq': (0, 0, 13, 20), 'wechat': (0, 0, 13, 20)}, file={'qq': 'templates/qq/icon/icon_steal_in_friend_detail.png', 'wechat': 'templates/qq/icon/icon_steal_in_friend_detail.png'}, name='icon_steal_in_friend_detail')
ICON_STEAL_IN_FRIEND_LIST = Button(area={'qq': (0, 0, 30, 28), 'wechat': (0, 0, 30, 28)}, color={'qq': (212, 188, 169), 'wechat': (212, 188, 169)}, button={'qq': (0, 0, 30, 28), 'wechat': (0, 0, 30, 28)}, file={'qq': 'templates/qq/icon/icon_steal_in_friend_list.png', 'wechat': 'templates/qq/icon/icon_steal_in_friend_list.png'}, name='icon_steal_in_friend_list')
ICON_WATER_IN_FRIEND_DETAIL = Button(area={'qq': (0, 0, 19, 11), 'wechat': (0, 0, 19, 11)}, color={'qq': (164, 167, 178), 'wechat': (164, 167, 178)}, button={'qq': (0, 0, 19, 11), 'wechat': (0, 0, 19, 11)}, file={'qq': 'templates/qq/icon/icon_water_in_friend_detail.png', 'wechat': 'templates/qq/icon/icon_water_in_friend_detail.png'}, name='icon_water_in_friend_detail')
ICON_WATER_IN_FRIEND_LIST = Button(area={'qq': (0, 0, 25, 23), 'wechat': (0, 0, 25, 23)}, color={'qq': (184, 186, 190), 'wechat': (184, 186, 190)}, button={'qq': (0, 0, 25, 23), 'wechat': (0, 0, 25, 23)}, file={'qq': 'templates/qq/icon/icon_water_in_friend_list.png', 'wechat': 'templates/qq/icon/icon_water_in_friend_list.png'}, name='icon_water_in_friend_list')
ICON_WEED_IN_FRIEND_DETAIL = Button(area={'qq': (0, 0, 14, 10), 'wechat': (0, 0, 14, 10)}, color={'qq': (106, 166, 61), 'wechat': (106, 166, 61)}, button={'qq': (0, 0, 14, 10), 'wechat': (0, 0, 14, 10)}, file={'qq': 'templates/qq/icon/icon_weed_in_friend_detail.png', 'wechat': 'templates/qq/icon/icon_weed_in_friend_detail.png'}, name='icon_weed_in_friend_detail')
ICON_WEED_IN_FRIEND_LIST = Button(area={'qq': (0, 0, 22, 22), 'wechat': (0, 0, 22, 22)}, color={'qq': (180, 192, 151), 'wechat': (180, 192, 151)}, button={'qq': (0, 0, 22, 22), 'wechat': (0, 0, 22, 22)}, file={'qq': 'templates/qq/icon/icon_weed_in_friend_list.png', 'wechat': 'templates/qq/icon/icon_weed_in_friend_list.png'}, name='icon_weed_in_friend_list')
MAIN_GOTO_FRIEND = Button(area={'qq': (448, 863, 493, 894), 'wechat': (448, 863, 493, 894)}, color={'qq': (221, 187, 122), 'wechat': (221, 187, 122)}, button={'qq': (448, 863, 493, 894), 'wechat': (448, 863, 493, 894)}, file={'qq': 'templates/qq/ui/main_goto_friend.png', 'wechat': 'templates/qq/ui/main_goto_friend.png'}, name='main_goto_friend')
MAIN_GOTO_MALL = Button(area={'qq': (474, 164, 505, 189), 'wechat': (474, 164, 505, 189)}, color={'qq': (184, 182, 97), 'wechat': (184, 182, 97)}, button={'qq': (474, 164, 505, 189), 'wechat': (474, 164, 505, 189)}, file={'qq': 'templates/qq/ui/main_goto_mall.png', 'wechat': 'templates/qq/ui/main_goto_mall.png'}, name='main_goto_mall')
MAIN_GOTO_MENU = Button(area={'qq': (32, 300, 49, 319), 'wechat': (32, 300, 49, 319)}, color={'qq': (229, 191, 127), 'wechat': (229, 191, 127)}, button={'qq': (32, 300, 49, 319), 'wechat': (32, 300, 49, 319)}, file={'qq': 'templates/qq/ui/main_goto_menu.png', 'wechat': 'templates/qq/ui/main_goto_menu.png'}, name='main_goto_menu')
MAIN_GOTO_PET = Button(area={'qq': (221, 861, 270, 895), 'wechat': (221, 861, 270, 895)}, color={'qq': (197, 174, 169), 'wechat': (197, 174, 169)}, button={'qq': (221, 861, 270, 895), 'wechat': (221, 861, 270, 895)}, file={'qq': 'templates/qq/ui/main_goto_pet.png', 'wechat': 'templates/qq/ui/main_goto_pet.png'}, name='main_goto_pet')
MAIN_GOTO_SHARE = Button(area={'qq': (34, 160, 59, 183), 'wechat': (34, 160, 59, 183)}, color={'qq': (205, 156, 99), 'wechat': (205, 156, 99)}, button={'qq': (34, 160, 59, 183), 'wechat': (34, 160, 59, 183)}, file={'qq': 'templates/qq/ui/main_goto_share.png', 'wechat': 'templates/qq/ui/main_goto_share.png'}, name='main_goto_share')
MAIN_GOTO_SHOP = Button(area={'qq': (126, 861, 175, 895), 'wechat': (126, 861, 175, 895)}, color={'qq': (222, 183, 98), 'wechat': (222, 183, 98)}, button={'qq': (126, 861, 175, 895), 'wechat': (126, 861, 175, 895)}, file={'qq': 'templates/qq/ui/main_goto_shop.png', 'wechat': 'templates/qq/ui/main_goto_shop.png'}, name='main_goto_shop')
MAIN_GOTO_TASK = Button(area={'qq': (34, 782, 64, 812), 'wechat': (34, 782, 64, 812)}, color={'qq': (222, 190, 149), 'wechat': (222, 190, 149)}, button={'qq': (34, 782, 64, 812), 'wechat': (34, 782, 64, 812)}, file={'qq': 'templates/qq/ui/main_goto_task.png', 'wechat': 'templates/qq/ui/main_goto_task.png'}, name='main_goto_task')
MAIN_GOTO_WAREHOUSE = Button(area={'qq': (30, 861, 79, 895), 'wechat': (30, 861, 79, 895)}, color={'qq': (217, 166, 99), 'wechat': (217, 166, 99)}, button={'qq': (30, 861, 79, 895), 'wechat': (30, 861, 79, 895)}, file={'qq': 'templates/qq/ui/main_goto_warehouse.png', 'wechat': 'templates/qq/ui/main_goto_warehouse.png'}, name='main_goto_warehouse')
MAIN_GOTO_WIKI = Button(area={'qq': (319, 868, 366, 895), 'wechat': (319, 868, 366, 895)}, color={'qq': (218, 163, 130), 'wechat': (218, 163, 130)}, button={'qq': (319, 868, 366, 895), 'wechat': (319, 868, 366, 895)}, file={'qq': 'templates/qq/ui/main_goto_wiki.png', 'wechat': 'templates/qq/ui/main_goto_wiki.png'}, name='main_goto_wiki')
MALL_CHECK = Button(area={'qq': (117, 83, 174, 112), 'wechat': (117, 83, 174, 112)}, color={'qq': (193, 156, 137), 'wechat': (193, 156, 137)}, button={'qq': (117, 83, 174, 112), 'wechat': (117, 83, 174, 112)}, file={'qq': 'templates/qq/ui/mall_check.png', 'wechat': 'templates/qq/ui/mall_check.png'}, name='mall_check')
MALL_GOTO_MAIN = Button(area={'qq': (44, 93, 82, 122), 'wechat': (44, 93, 82, 122)}, color={'qq': (230, 187, 117), 'wechat': (230, 187, 117)}, button={'qq': (44, 93, 82, 122), 'wechat': (44, 93, 82, 122)}, file={'qq': 'templates/qq/ui/mall_goto_main.png', 'wechat': 'templates/qq/ui/mall_goto_main.png'}, name='mall_goto_main')
MENU_GOTO_MAIN = Button(area={'qq': (31, 300, 51, 319), 'wechat': (31, 300, 51, 319)}, color={'qq': (244, 210, 136), 'wechat': (244, 210, 136)}, button={'qq': (31, 300, 51, 319), 'wechat': (31, 300, 51, 319)}, file={'qq': 'templates/qq/ui/menu_goto_main.png', 'wechat': 'templates/qq/ui/menu_goto_main.png'}, name='menu_goto_main')
PET_CHECK = Button(area={'qq': (241, 77, 294, 105), 'wechat': (241, 77, 294, 105)}, color={'qq': (232, 199, 181), 'wechat': (232, 199, 181)}, button={'qq': (241, 77, 294, 105), 'wechat': (241, 77, 294, 105)}, file={'qq': 'templates/qq/ui/pet_check.png', 'wechat': 'templates/qq/ui/pet_check.png'}, name='pet_check')
SEED_BTN_HEART_FRUIT = Button(area={'qq': (81, 613, 120, 637), 'wechat': (81, 613, 120, 637)}, color={'qq': (243, 176, 78), 'wechat': (243, 176, 78)}, button={'qq': (81, 613, 120, 637), 'wechat': (81, 613, 120, 637)}, file={'qq': 'templates/qq/seedbtn/seed_btn_heart_fruit.png', 'wechat': 'templates/qq/seedbtn/seed_btn_heart_fruit.png'}, name='seed_btn_heart_fruit')
SETTING_CHECK = Button(area={'qq': (31, 607, 53, 632), 'wechat': (31, 607, 53, 632)}, color={'qq': (227, 183, 122), 'wechat': (227, 183, 122)}, button={'qq': (31, 607, 53, 632), 'wechat': (31, 607, 53, 632)}, file={'qq': 'templates/qq/ui/setting_check.png', 'wechat': 'templates/qq/ui/setting_check.png'}, name='setting_check')
SHOP_CHECK = Button(area={'qq': (241, 85, 298, 113), 'wechat': (241, 85, 298, 113)}, color={'qq': (225, 191, 168), 'wechat': (225, 191, 168)}, button={'qq': (241, 85, 298, 113), 'wechat': (241, 85, 298, 113)}, file={'qq': 'templates/qq/ui/shop_check.png', 'wechat': 'templates/qq/ui/shop_check.png'}, name='shop_check')
TASK_CHECK = Button(area={'qq': (242, 87, 298, 115), 'wechat': (242, 87, 298, 115)}, color={'qq': (224, 188, 165), 'wechat': (224, 188, 165)}, button={'qq': (242, 87, 298, 115), 'wechat': (242, 87, 298, 115)}, file={'qq': 'templates/qq/ui/task_check.png', 'wechat': 'templates/qq/ui/task_check.png'}, name='task_check')
WAREHOUSE_CHECK = Button(area={'qq': (242, 70, 298, 98), 'wechat': (242, 70, 298, 98)}, color={'qq': (226, 188, 168), 'wechat': (226, 188, 168)}, button={'qq': (242, 70, 298, 98), 'wechat': (242, 70, 298, 98)}, file={'qq': 'templates/qq/ui/warehouse_check.png', 'wechat': 'templates/qq/ui/warehouse_check.png'}, name='warehouse_check')
WIKI_CHECK = Button(area={'qq': (244, 72, 298, 98), 'wechat': (244, 72, 298, 98)}, color={'qq': (233, 206, 186), 'wechat': (233, 206, 186)}, button={'qq': (244, 72, 298, 98), 'wechat': (244, 72, 298, 98)}, file={'qq': 'templates/qq/ui/wiki_check.png', 'wechat': 'templates/qq/ui/wiki_check.png'}, name='wiki_check')

ASSET_NAME_TO_CONST = {
    'btn_batch_sell': BTN_BATCH_SELL,
    'btn_bug': BTN_BUG,
    'btn_claim': BTN_CLAIM,
    'btn_click_to_close': BTN_CLICK_TO_CLOSE,
    'btn_close': BTN_CLOSE,
    'btn_come_again': BTN_COME_AGAIN,
    'btn_confirm': BTN_CONFIRM,
    'btn_expand': BTN_EXPAND,
    'btn_expand_confirm': BTN_EXPAND_CONFIRM,
    'btn_expand_direct_confirm': BTN_EXPAND_DIRECT_CONFIRM,
    'btn_friend_agreed': BTN_FRIEND_AGREED,
    'btn_friend_apply': BTN_FRIEND_APPLY,
    'btn_friend_right_frame': BTN_FRIEND_RIGHT_FRAME,
    'btn_harvest': BTN_HARVEST,
    'btn_home': BTN_HOME,
    'btn_labor_is_glorious': BTN_LABOR_IS_GLORIOUS,
    'btn_land_left': BTN_LAND_LEFT,
    'btn_land_right': BTN_LAND_RIGHT,
    'btn_login_again': BTN_LOGIN_AGAIN,
    'btn_mature': BTN_MATURE,
    'btn_ordinary_fertilizer': BTN_ORDINARY_FERTILIZER,
    'btn_organic_fertilizer': BTN_ORGANIC_FERTILIZER,
    'btn_planting': BTN_PLANTING,
    'BTN_SEED_SELECT_POPUP_RIGHT': BTN_SEED_SELECT_POPUP_RIGHT,
    'btn_share_green': BTN_SHARE_GREEN,
    'btn_share_yellow': BTN_SHARE_YELLOW,
    'btn_shop_buy_check': BTN_SHOP_BUY_CHECK,
    'btn_shop_buy_confirm': BTN_SHOP_BUY_CONFIRM,
    'btn_steal': BTN_STEAL,
    'btn_task_claim': BTN_TASK_CLAIM,
    'btn_visit_first': BTN_VISIT_FIRST,
    'btn_water': BTN_WATER,
    'btn_weed': BTN_WEED,
    'friend_check': FRIEND_CHECK,
    'icon_bug_in_friend_detail': ICON_BUG_IN_FRIEND_DETAIL,
    'icon_bug_in_friend_list': ICON_BUG_IN_FRIEND_LIST,
    'icon_land_black': ICON_LAND_BLACK,
    'icon_land_gold': ICON_LAND_GOLD,
    'icon_land_gold_2': ICON_LAND_GOLD_2,
    'icon_land_red': ICON_LAND_RED,
    'icon_land_stand': ICON_LAND_STAND,
    'icon_num_0': ICON_NUM_0,
    'icon_num_1': ICON_NUM_1,
    'icon_num_2': ICON_NUM_2,
    'icon_num_3': ICON_NUM_3,
    'icon_num_4': ICON_NUM_4,
    'icon_num_5': ICON_NUM_5,
    'icon_num_6': ICON_NUM_6,
    'icon_num_7': ICON_NUM_7,
    'icon_num_8': ICON_NUM_8,
    'icon_num_9': ICON_NUM_9,
    'icon_num_left': ICON_NUM_LEFT,
    'icon_steal_in_friend_detail': ICON_STEAL_IN_FRIEND_DETAIL,
    'icon_steal_in_friend_list': ICON_STEAL_IN_FRIEND_LIST,
    'icon_water_in_friend_detail': ICON_WATER_IN_FRIEND_DETAIL,
    'icon_water_in_friend_list': ICON_WATER_IN_FRIEND_LIST,
    'icon_weed_in_friend_detail': ICON_WEED_IN_FRIEND_DETAIL,
    'icon_weed_in_friend_list': ICON_WEED_IN_FRIEND_LIST,
    'main_goto_friend': MAIN_GOTO_FRIEND,
    'main_goto_mall': MAIN_GOTO_MALL,
    'main_goto_menu': MAIN_GOTO_MENU,
    'main_goto_pet': MAIN_GOTO_PET,
    'main_goto_share': MAIN_GOTO_SHARE,
    'main_goto_shop': MAIN_GOTO_SHOP,
    'main_goto_task': MAIN_GOTO_TASK,
    'main_goto_warehouse': MAIN_GOTO_WAREHOUSE,
    'main_goto_wiki': MAIN_GOTO_WIKI,
    'mall_check': MALL_CHECK,
    'mall_goto_main': MALL_GOTO_MAIN,
    'menu_goto_main': MENU_GOTO_MAIN,
    'pet_check': PET_CHECK,
    'seed_btn_heart_fruit': SEED_BTN_HEART_FRUIT,
    'setting_check': SETTING_CHECK,
    'shop_check': SHOP_CHECK,
    'task_check': TASK_CHECK,
    'warehouse_check': WAREHOUSE_CHECK,
    'wiki_check': WIKI_CHECK,
}
