"""模板提取为 UI assets（排除 seed），按平台生成并回退默认平台。

对齐 NIKKE 逻辑：
- 先生成默认平台（qq）
- 其他平台（wechat）缺失时回退 qq 的 area/color/button/file
- 最终 assets.py 中每个 Button 字段为平台字典
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageSequence

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.app_paths import load_config_json_object
from utils.template_paths import (
    DEFAULT_TEMPLATE_PLATFORM,
    VALID_TEMPLATE_PLATFORMS,
    normalize_template_platform,
    template_scan_roots,
)

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES_DIR = ROOT / 'templates'
OUTPUT_PATH = ROOT / 'core' / 'ui' / 'assets.py'
OVERRIDE_SUFFIXES = {'AREA', 'COLOR', 'BUTTON'}
SUPPORTED_PLATFORMS = [DEFAULT_TEMPLATE_PLATFORM] + sorted(
    p for p in VALID_TEMPLATE_PLATFORMS if p != DEFAULT_TEMPLATE_PLATFORM
)
SUPPORTED_IMAGE_EXTS = {'.png', '.gif'}


HEADER = """from core.base.button import Button

# This file was automatically generated by tools/button_extract.py.
# Do not modify it manually.
"""


@dataclass
class Item:
    """单个按钮资源项（包含多平台字段）。"""

    name: str
    area: dict[str, tuple[int, int, int, int]]
    color: dict[str, tuple[int, int, int]]
    button: dict[str, tuple[int, int, int, int]]
    file_rel: dict[str, str]
    alias: str


@dataclass
class SourceBundle:
    """单平台单名称的模板来源（含 override）。"""

    base: Path | None = None
    area: Path | None = None
    color: Path | None = None
    button: Path | None = None
    base_rel: str = ''
    base_priority: int = -1
    area_priority: int = -1
    color_priority: int = -1
    button_priority: int = -1


def load_aliases() -> dict[str, str]:
    """读取按钮别名配置。"""
    aliases = load_config_json_object('button_aliases.json', prefer_user=False)
    return {str(k): str(v) for k, v in aliases.items()}


def extract_bbox_and_color(image_path: Path) -> tuple[tuple[int, int, int, int], tuple[int, int, int]]:
    """提取非黑像素 bbox 与均值颜色（RGB）。"""

    if image_path.suffix.lower() == '.gif':
        return _extract_gif_bbox_and_color(image_path)
    bgr = _load_image_as_bgr(image_path)
    if bgr is None:
        return (0, 0, 1, 1), (128, 128, 128)
    return _extract_bbox_and_color_from_bgr(bgr)


def _extract_gif_bbox_and_color(image_path: Path) -> tuple[tuple[int, int, int, int], tuple[int, int, int]]:
    """提取 GIF 的 bbox 与颜色（按首帧，帧间 bbox 不一致时告警）。"""

    first_bbox: tuple[int, int, int, int] | None = None
    first_color: tuple[int, int, int] | None = None
    try:
        with Image.open(image_path) as gif:
            for frame in ImageSequence.Iterator(gif):
                rgb = frame.convert('RGB')
                arr = np.array(rgb)
                bgr = cv2.cvtColor(arr, cv2.COLOR_RGB2BGR)
                bbox, color = _extract_bbox_and_color_from_bgr(bgr)
                if first_bbox is None:
                    first_bbox = bbox
                    first_color = color
                    continue
                if bbox != first_bbox:
                    print(f'[button_extract] warning: gif bbox differs across frames: {image_path}')
    except Exception as exc:
        print(f'[button_extract] warning: failed to read gif {image_path}: {exc}')
    if first_bbox is None or first_color is None:
        return (0, 0, 1, 1), (128, 128, 128)
    return first_bbox, first_color


def _extract_bbox_and_color_from_bgr(bgr: np.ndarray) -> tuple[tuple[int, int, int, int], tuple[int, int, int]]:
    """从 BGR 图像提取非黑像素 bbox 与均值颜色（RGB）。"""

    if bgr.ndim == 2:
        bgr = cv2.cvtColor(bgr, cv2.COLOR_GRAY2BGR)
    elif bgr.ndim == 3 and bgr.shape[2] > 3:
        bgr = bgr[:, :, :3]

    mask = np.any(bgr > 0, axis=2)
    ys, xs = np.where(mask)
    if len(xs) == 0 or len(ys) == 0:
        h, w = bgr.shape[:2]
        return (0, 0, max(1, w), max(1, h)), (128, 128, 128)

    x1 = int(xs.min())
    y1 = int(ys.min())
    x2 = int(xs.max() + 1)
    y2 = int(ys.max() + 1)

    roi = bgr[y1:y2, x1:x2]
    if roi.size == 0:
        mean_rgb = (128, 128, 128)
    else:
        mean_bgr = roi.mean(axis=(0, 1))
        mean_rgb = (int(round(mean_bgr[2])), int(round(mean_bgr[1])), int(round(mean_bgr[0])))
    return (x1, y1, x2, y2), mean_rgb


def image_wh(image_path: Path) -> tuple[int, int] | None:
    """读取图片宽高。"""

    if image_path.suffix.lower() == '.gif':
        try:
            with Image.open(image_path) as gif:
                width, height = gif.size
                return int(width), int(height)
        except Exception:
            return None
    img = _load_image_as_bgr(image_path)
    if img is None:
        return None
    h, w = img.shape[:2]
    return int(w), int(h)


def _load_image_as_bgr(image_path: Path) -> np.ndarray | None:
    """读取图片并归一化为 3 通道 BGR（非 GIF）。"""

    img = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
    if img is None:
        return None
    if img.ndim == 2:
        return cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    if img.ndim == 3 and img.shape[2] > 3:
        return img[:, :, :3]
    return img


def to_const_name(template_name: str) -> str:
    """模板名转常量名。"""

    if template_name.startswith('btn_'):
        return 'BTN_' + template_name[4:].upper()
    if template_name.startswith('icon_'):
        return 'ICON_' + template_name[5:].upper()
    if template_name.startswith('land_'):
        return 'LAND_' + template_name[5:].upper()
    safe = ''.join(ch if ch.isalnum() else '_' for ch in template_name).upper()
    return safe


def parse_template_name(path: Path) -> tuple[str, str]:
    """解析模板名与 override 类型。"""

    stem = path.stem
    if '.' not in stem:
        return stem, 'BASE'
    base, suffix = stem.rsplit('.', 1)
    suffix = suffix.upper()
    if suffix in OVERRIDE_SUFFIXES:
        return base, suffix
    return stem, 'BASE'


def _iter_files_in_root(root: Path):
    """遍历指定根目录下模板文件。"""

    ignored = {'__pycache__'}
    root_str = str(root)
    for walk_root, dirs, files in os.walk(root_str):
        rel = os.path.relpath(walk_root, root_str)
        if rel == '.':
            dirs[:] = [d for d in dirs if d.lower() not in ignored]
        else:
            top = rel.split(os.sep, 1)[0].lower()
            if top in ignored:
                continue
            dirs[:] = [d for d in dirs if d.lower() not in ignored]

        for filename in sorted(files):
            if Path(filename).suffix.lower() in SUPPORTED_IMAGE_EXTS:
                yield Path(walk_root) / filename


def collect_sources_for_platform(platform: str) -> dict[str, SourceBundle]:
    """按平台收集模板来源，后扫描目录覆盖前扫描目录。"""

    selected = normalize_template_platform(platform)
    bundles: dict[str, SourceBundle] = {}
    roots = template_scan_roots(selected, str(TEMPLATES_DIR))
    for priority, root in enumerate(roots, start=1):
        root = Path(root)
        if not root.exists():
            continue
        for path in _iter_files_in_root(root):
            rel = path.relative_to(TEMPLATES_DIR).as_posix()
            if rel.startswith('seed/'):
                continue
            if rel.startswith('qq/seed/') or rel.startswith('wechat/seed/'):
                continue

            name, kind = parse_template_name(path)
            bundle = bundles.setdefault(name, SourceBundle())
            if kind == 'BASE':
                if (
                    bundle.base is None
                    or priority > bundle.base_priority
                    or (
                        priority == bundle.base_priority
                        and _image_ext_priority(path) > _image_ext_priority(bundle.base)
                    )
                ):
                    bundle.base = path
                    bundle.base_rel = f'templates/{rel}'
                    bundle.base_priority = int(priority)
                continue

            key = kind.lower()
            priority_key = f'{key}_priority'
            current = getattr(bundle, key)
            current_priority = int(getattr(bundle, priority_key))
            if (
                current is None
                or priority > current_priority
                or (priority == current_priority and _image_ext_priority(path) > _image_ext_priority(current))
            ):
                setattr(bundle, key, path)
                setattr(bundle, priority_key, int(priority))
    return bundles


def _image_ext_priority(path: Path | None) -> int:
    """同优先级下图片扩展名选择策略：png 优先于 gif。"""

    if path is None:
        return -1
    ext = path.suffix.lower()
    if ext == '.png':
        return 2
    if ext == '.gif':
        return 1
    return 0


def _extract_bundle_values(
    bundle: SourceBundle,
) -> tuple[tuple[int, int, int, int], tuple[int, int, int], tuple[int, int, int, int], str] | None:
    """从 bundle 提取 area/color/button/file。"""

    if bundle.base is None:
        return None
    rel = bundle.base_rel or bundle.base.relative_to(ROOT).as_posix()
    area, color = extract_bbox_and_color(bundle.base)
    button = area

    if bundle.area is not None:
        area, _ = extract_bbox_and_color(bundle.area)
    if bundle.color is not None:
        _, color = extract_bbox_and_color(bundle.color)
    if bundle.button is not None:
        button, _ = extract_bbox_and_color(bundle.button)
    return area, color, button, rel


def build_items() -> list[Item]:
    """按默认平台生成资产清单，并补齐其他平台回退字段。"""

    alias_by_name = load_aliases()
    platform_bundles = {p: collect_sources_for_platform(p) for p in SUPPORTED_PLATFORMS}
    default_bundles = platform_bundles[DEFAULT_TEMPLATE_PLATFORM]

    items: list[Item] = []
    for name in sorted(default_bundles.keys()):
        default_values = _extract_bundle_values(default_bundles[name])
        if default_values is None:
            print(f'[button_extract] missing base image, skipped: {name}')
            continue
        def_area, def_color, def_button, def_file = default_values

        # 保留原有 full-frame 诊断提示
        base_path = default_bundles[name].base
        if base_path is not None:
            size = image_wh(base_path)
            if (
                size is not None
                and default_bundles[name].area is None
                and default_bundles[name].button is None
                and size[0] >= 300
                and size[1] >= 500
                and def_area == (0, 0, size[0], size[1])
            ):
                print(f'[button_extract] full-frame bbox: {name} (consider {name}.AREA.png / {name}.BUTTON.png)')

        area_map: dict[str, tuple[int, int, int, int]] = {}
        color_map: dict[str, tuple[int, int, int]] = {}
        button_map: dict[str, tuple[int, int, int, int]] = {}
        file_map: dict[str, str] = {}

        for platform in SUPPORTED_PLATFORMS:
            values = None
            bundle = platform_bundles.get(platform, {}).get(name)
            if bundle is not None:
                values = _extract_bundle_values(bundle)
            if values is None:
                values = (def_area, def_color, def_button, def_file)

            area_map[platform] = values[0]
            color_map[platform] = values[1]
            button_map[platform] = values[2]
            file_map[platform] = values[3]

        alias = str(alias_by_name.get(name, '')).strip()
        items.append(
            Item(
                name=name,
                area=area_map,
                color=color_map,
                button=button_map,
                file_rel=file_map,
                alias=alias,
            )
        )
    return items


def _render_value_dict(mapping: dict[str, object], *, as_string: bool = False) -> str:
    """渲染平台字典为稳定文本。"""

    parts: list[str] = []
    for platform in SUPPORTED_PLATFORMS:
        value = mapping[platform]
        if as_string:
            parts.append(f"'{platform}': '{value}'")
        else:
            parts.append(f"'{platform}': {value}")
    return '{' + ', '.join(parts) + '}'


def render(items: list[Item]) -> str:
    """渲染 assets.py 文本。"""

    lines = [HEADER.rstrip(), '']
    rendered: dict[str, str] = {}
    for item in items:
        const_name = to_const_name(item.name)
        base = const_name
        idx = 2
        while const_name in rendered:
            const_name = f'{base}_{idx}'
            idx += 1
        rendered[const_name] = item.name

        area_expr = _render_value_dict(item.area)
        color_expr = _render_value_dict(item.color)
        button_expr = _render_value_dict(item.button)
        file_expr = _render_value_dict(item.file_rel, as_string=True)

        comment = f'  # {item.alias}' if item.alias else ''
        lines.append(
            f'{const_name} = Button(area={area_expr}, color={color_expr}, button={button_expr}, '
            f"file={file_expr}, name='{item.name}'){comment}"
        )

    lines.append('')
    lines.append('ASSET_NAME_TO_CONST = {')
    for const_name, asset_name in sorted(rendered.items()):
        lines.append(f"    '{asset_name}': {const_name},")
    lines.append('}')
    lines.append('')
    return '\n'.join(lines)


def main():
    """程序主入口。"""

    items = build_items()
    text = render(items)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text, encoding='utf-8')
    print(f'[button_extract] generated: {OUTPUT_PATH} (items={len(items)})')


if __name__ == '__main__':
    main()
